### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ma14uk** [hippiiee/osgint#6]
```

 .d88888b.                    d8b          888    
d88P" "Y88b                   Y8P          888    
888     888                                888    
888     888 .d8888b   .d88b.  888 88888b.  888888 
888     888 88K      d88P"88b 888 888 "88b 888    
888     888 "Y8888b. 888  888 888 888  888 888    
Y88b. .d88P      X88 Y88b 888 888 888  888 Y88b.  
 "Y88888P"   88888P'  "Y88888 888 888  888  "Y888 
                          888  v1.0.3
                     Y8b d88P                     
                      "Y88P"                      
By Hippie | https://twitter.com/hiippiiie

Traceback (most recent call last):
  File "/Users/mmalchuk/Dropbox/Repos/osgint/./osgint.py", line 148, in <module>
    findPublicKeysFromUsername(args.username)
  File "/Users/mmalchuk/Dropbox/Repos/osgint/./osgint.py", line 75, in findPublicKeysFromUsername
    matches = regex_pgp.findall(gpg_response)[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by ma14uk** [comment]
this happens when github.com reply with an erroneous gpg keys from user like:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Note: The keys with the following IDs couldn't be exported and need to be reuploaded...
-----END PGP PUBLIC KEY BLOCK-----

```

**Comment by hippiiee** [comment]
Hi, thank you for the issue. Can you provide me a user which has this error so I can reproduce it locally ?
Thanks :)

**Comment by ma14uk** [comment]
Hi @hippiiee, this is my primary account that I can't restore. It has an old GPG key which I can't replace.
